### PR TITLE
Tensorflow 2 support added with custom node feature

### PR DESCRIPTION
**Pull request by nKandel**
This changes the work done by Narayan Kandel and Boqiang Li as part of internship '23. The changes include.
 - Update GNN bundle to Tensorflow 2.x
 - Add the function of saving model and loading model.
 - Add support for the pre-trained models.
 - Add unit test for newly created functions.
 - GPU acceleration is supported.
 - Control node number to run training of the neural network.

Known Bug: IFF isn't doing a lazy evaluation on the Fit() function. Currently, both (`OneNodeFit`, `nNodeFit`) gets evaluated.

### CODE REVIEW

**Comment by nKandel** [comment]
Hi @RogerDev, @lilyclemson. I have created a pull request with my code and @littlesevenmo's code. Please, let me know your suggestion regarding the changes that are required for this pull request.

**Comment by boqiang-li** [comment]
Hi @nKandel, Thanks for your code. I checked the code. I found there is still nesting between commits. Please fix it.
I suggest that the commit should be something like this:

[My commit]Update GNN bundle to Tensorflow 2.x
[Your commit]......

I found that both commit,  [import python3 instead of python](https://github.com/hpcc-systems/GNN/pull/12/commits/b75cd1ac2b711f450fb20a6639dc7a8f371f6666) and [Update GNN bundle to Tensorflow 2.x.](https://github.com/hpcc-systems/GNN/pull/12/commits/aafd3b1b43818227bc066a2988f8ee44cf925a5d), replace `IMPORT Python;` in TensTest.ecl and ExtractTest.ecl with `IMPORT Python3 AS Python;` Please check it.

If I'm correct, we shouldn't need this commit [import python3 instead of python](https://github.com/hpcc-systems/GNN/pull/12/commits/b75cd1ac2b711f450fb20a6639dc7a8f371f6666).

**Comment by nKandel** [comment]
Hi @lilyclemson, I have reformatted the code according to your comment. Please let me know if you have any other recommendations.

**Review by RogerDev — APPROVED** [review]

**Review by RogerDev — APPROVED** [review]

**Comment by RogerDev** [comment]
@ghalliday Please merge.  This is the work of both GNN interns.

**Pull request merged**
